--CLASSIFICAÇÃO
    SELECT MEX.DTCOLHEITA, TOT.PESOTOTAL, ROUND(MEX.PESO/TOT.PESOTOTAL100,1) AS PERCME, ROUND(MINT.PESO/TOT.PESOTOTAL100,1) AS PERCMI, MEX.PESO AS PESO_ME, MINT.PESO AS PESO_MI
    FROM
        (
        SELECT TO_CHAR(DTCOLHEITA, 'YYYY') DTCOLHEITA, SUM(ME.QTDCLAS) AS PESO, 'ME' AS TIPO
        FROM AD_TITACLA ME
        INNER JOIN AD_TITALAVCLA LAV ON ME.ID = LAV.ID
        WHERE TO_CHAR(TRUNC(LAV.DTCOLHEITA), 'YYYY') = 2022
         AND ME.DTFINALIZACAO IS NOT NULL
        GROUP BY TO_CHAR(DTCOLHEITA, 'YYYY')
        ) MEX

    INNER JOIN

        (
        SELECT TO_CHAR(DTCOLHEITA, 'YYYY') DTCOLHEITA, SUM(MI.PESO) AS PESO, 'MI' AS TIPO
        FROM AD_TITACLAMI MI
        INNER JOIN AD_TITALAVCLA LAV ON MI.ID = LAV.ID
        WHERE  TO_CHAR(TRUNC(LAV.DTCOLHEITA), 'YYYY') = 2022
         AND MI.DTFINALIZACAO IS NOT NULL
         AND MI.IDCAL <> 8
        GROUP BY  TO_CHAR(DTCOLHEITA, 'YYYY')
        ) MINT ON MINT.DTCOLHEITA = MEX.DTCOLHEITA

    INNER JOIN
        (
        SELECT  DTCOLHEITA, SUM(PESO) AS PESOTOTAL FROM
            (
            --CLASSIFICAÇÃO
            SELECT TO_CHAR(DTCOLHEITA, 'YYYY') DTCOLHEITA, SUM(ME.QTDCLAS) AS PESO
            FROM AD_TITACLA ME
            INNER JOIN AD_TITALAVCLA LAV ON ME.ID = LAV.ID
            WHERE TO_CHAR(TRUNC(LAV.DTCOLHEITA), 'YYYY') = 2022
             AND ME.DTFINALIZACAO IS NOT NULL
            GROUP BY TO_CHAR(DTCOLHEITA, 'YYYY')

            UNION ALL

            SELECT TO_CHAR(DTCOLHEITA, 'YYYY') DTCOLHEITA, SUM(MI.PESO) AS PESO
            FROM AD_TITACLAMI MI
            INNER JOIN AD_TITALAVCLA LAV ON MI.ID = LAV.ID
            WHERE TO_CHAR(TRUNC(LAV.DTCOLHEITA), 'YYYY') = 2022
             AND MI.DTFINALIZACAO IS NOT NULL
              AND MI.IDCAL <> 8
            GROUP BY TO_CHAR(DTCOLHEITA, 'YYYY')
            )
        GROUP BY DTCOLHEITA
        ) TOT ON MEX.DTCOLHEITA = TOT.DTCOLHEITA