SELECT CODPROD, DESCRPROD, CUSTO, NUNOTA, QTDNEG, CODVOL, QTDNEG * CUSTO AS CUSTO_TOTAL FROM
(SELECT ITE.CODPROD, PRO.DESCRPROD, SNK_GET_CUSTO('MEDIOSEMICMS', 1, ITE.CODPROD, ITE.CODLOCALORIG, ITE.CONTROLE, CAB.DTENTSAI) CUSTO, CAB.NUNOTA, ITE.QTDNEG, ITE.CODVOL FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE CAB.OBSERVACAO LIKE '%10034%')